#!/usr/bin/env bash
#
# Build telemetry binaries in Docker container.
#

set -euo pipefail

# declare BASE_IMAGE="hkjn/golang:$(uname -m)-tip"
declare BUILD_IMAGE="hkjn/workspace:$(uname -m)-zero-1.1.3"
declare BUILD_DIR="$(mktemp -d)"
declare BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${BASE_DIR}"

echo "Building in ${BUILD_IMAGE}.."
sed "s|{{ARG_FROM}}|${BUILD_IMAGE}|g" Dockerfile.build > ${BUILD_DIR}/Dockerfile
cp -r {client,server,report,vendor} ${BUILD_DIR}
echo "package main" > ${BUILD_DIR}/client/version.go
echo "const Version=\"$(cat ../VERSION)\"" >> ${BUILD_DIR}/client/version.go

echo "package main" > ${BUILD_DIR}/server/version.go
echo "const Version=\"$(cat ../VERSION)\"" >> ${BUILD_DIR}/server/version.go

# TODO: Use heredoc or set build parameter as argument.
docker build -t telemetry-build ${BUILD_DIR}
docker run --name tbuild telemetry-build
rm -rf bin/
docker cp tbuild:/home/go/bin/ $(pwd)
docker rm tbuild
mv -v bin/* .
mv -v bin/report/*.pb.go report/
